apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: webserver
    tool: prometheus
    webserver: nginx
spec:
  containers:
  - name: prometheus
    image: gianniskl/prometheus
    ports:
    - containerPort: 8080
  - name: nginx
    image: nginx
    - containerPort: 80
    
